Require Spin app names to have at least 5 characters
Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>

diff --git a/k8s b/k8s
--- a/k8s
+++ b/k8s
@@ -188,6 +188,11 @@ build () {
         esac
     done
     NAME=`grep name spin.toml | cut -d'"' -f 2`
+    # Trimming fails for names shorter than 5 characters
+    if [ ${#NAME} -lt 5 ]; then
+        echo "Spin app name must be at least five characters to use k8s plugin"
+        exit 1
+    fi
     VERSION=`grep ^version spin.toml | cut -d'"' -f 2`
     TRIM=$((${#NAME} + ${#VERSION} + 3))
     NAMESPACE=`grep image deploy.yaml | cut -d' ' -f 12 | rev | cut -c$TRIM- | rev`
